<a href="https://colab.research.google.com/github/Sabelo-Sabs/Practice/blob/main/Matrices_and_Their_Attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Making Matrices

In [3]:
import numpy as np

In [7]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9],
       [10,12,13]]

In [10]:
matrix = np.array(lst)
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [9]:
#Matrix back to list
matrix.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 12, 13]]

In [11]:
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [12]:
# first row
matrix[0]

array([1, 2, 3])

In [13]:
#modifying the first row
matrix[0] = np.array([3,5,8])

In [14]:
matrix #modified version

array([[ 3,  5,  8],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [15]:
matrix[2,1] # second index row and first index column number

8

In [16]:
#Reassigning specific indices
matrix[2,0] = 12 #Assigning 7 to be 12

In [17]:
matrix

array([[ 3,  5,  8],
       [ 4,  5,  6],
       [12,  8,  9],
       [10, 12, 13]])

In [18]:
#All the rows and 2 column
matrix[:, 2]

array([ 8,  6,  9, 13])

-----

# Attributes

In [19]:
vector = np.arange(5)

In [20]:
vector.ndim #Number of dimensions

1

In [21]:
matrix.ndim

2

In [22]:
matrix.dtype #datatype

dtype('int64')

In [23]:
matrix.size # number of elements

12

In [24]:
matrix.shape # shape of matrix (R,C) RxC =4 rows and 3 columns

(4, 3)

----------------