<a href="https://colab.research.google.com/github/Sabelo-Sabs/Practice/blob/main/Numpy_Working_with_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical Python
## Creating Vectors and Extracting values from them.

In [1]:
import numpy as np # importing numpy

In [2]:
lst = [1,2,3,4,5,6,7,8,9,0]
array = np.array(lst)
array # making an array from a list

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
# Extracting Values
first_element = array[0]
last_element = array[-1]

In [4]:
first_element

1

In [5]:
last_element

0

In [6]:
#Setting Values
array[-1] = 10
array # Changed the last item to number 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#Creating Vectors with np.arange
seq_nums = np.arange(0,101,2) # Even numbers from 0 to 100
seq_nums

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

------

# Basic Operations

In [17]:
first = np.arange(1,6)
Second = np.arange(1,10,2)

In [18]:
first

array([1, 2, 3, 4, 5])

In [19]:
Second

array([1, 3, 5, 7, 9])

In [20]:
#Addition
sum_ = first + Second
print("sum:", sum_)

sum: [ 2  5  8 11 14]


In [21]:
#Subtraction
sum_ = first - Second
print("difference:", sum_)

difference: [ 0 -1 -2 -3 -4]


In [22]:
#Multiplication
sum_ = first * Second
print("Product:", sum_)

Product: [ 1  6 15 28 45]


In [24]:
#Division
sum_ = np.around(first / Second,2)
print("Division:", sum_)

Division: [1.   0.67 0.6  0.57 0.56]


In [25]:
#Exponential
sum_ = first ** Second
print("Exponential:", sum_)

Exponential: [      1       8     243   16384 1953125]


----
