<a href="https://colab.research.google.com/github/Sabelo-Sabs/Practice/blob/main/NumpyDataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Data Types

In [3]:
import numpy as np

In [6]:
#What datatypes does numpy have?
dt =np.array([1,2,4,6,77,54,5,75])
dt.dtype

dtype('int64')

In [7]:
#We can specify the dataypes if we want to take control
data =np.array([4,6,77,54,75], dtype= np.int8)
data.dtype

dtype('int8')

In [8]:
#Size of a vector
data.size

5

In [9]:
#Number of bytes used
data.nbytes

5

-----

# Slicing

In [11]:
#New array
array = np.array([3,4,6,1,8,5,89])
array

array([ 3,  4,  6,  1,  8,  5, 89])

In [12]:
#slice everything
array[:]

array([ 3,  4,  6,  1,  8,  5, 89])

In [13]:
#Everything after an index
array[2:]

array([ 6,  1,  8,  5, 89])

In [14]:
#Everything before an index
array[:4]

array([3, 4, 6, 1])

In [15]:
#Inbetween indices
array[2:5]

array([6, 1, 8])

In [16]:
#reverse an array
array[::-1]

array([89,  5,  8,  1,  6,  4,  3])