<a href="https://colab.research.google.com/github/Sabelo-Sabs/Practice/blob/main/Sorting_and_Aggregate_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Two ways of sorting arrays in numpy

### First way

In [7]:
import numpy as np
dt = np.array([12,1,6,3,9,22,689,45])
dt

array([ 12,   1,   6,   3,   9,  22, 689,  45])

In [3]:
#.sort() method, sorts the array in-place; meaning it sorts the origial vector
dt.sort()

In [4]:
dt

array([  1,   3,   6,   9,  12,  22,  45, 689])

### Second way

In [8]:
# np.sort() this function returns a sorted array
dt_sorted = np.sort(dt)

In [9]:
dt

array([ 12,   1,   6,   3,   9,  22, 689,  45])

In [10]:
dt_sorted

array([  1,   3,   6,   9,  12,  22,  45, 689])

------

# Copies VS Views

In [11]:
#Reverse an array
array = np.array([2,5,7,2,64])
arr_reversed = array[::-1]

#modify the reversed arry
arr_reversed[0] = 10
print("Modified:", arr_reversed)
print("Original:", array)

Modified: [10  2  7  5  2]
Original: [ 2  5  7  2 10]


In [12]:
#Looking the above cell both original and modified are modified. This is because slicing created a 'view'
# modification on a slice also affects the original array

In [14]:
#Make all elements positive
array_1 = np.array([-2,36,23,57,86,22,12])
array_1pos = np.abs(array_1)

array_1pos[0] = 33
print("modified", array_1pos)
print("Original", array_1)

modified [33 36 23 57 86 22 12]
Original [-2 36 23 57 86 22 12]


In [ ]:
#np.abs() this returns a copy!

-----

# Aggregate Functions

In [15]:
#We'll use the previous array we've used.
array

array([ 2,  5,  7,  2, 10])

In [17]:
#Let's take the sum of our array.
sum_array = np.sum(array)
print("Sum:", sum_array)

Sum: 26


In [18]:
#The mean.
mean_array = np.mean(array)

In [20]:
print("Average:", mean_array)

Average: 5.2


In [21]:
#Product of an array
product_array = np.prod(array)
print("Product:", product_array)

Product: 1400


In [23]:
#max/min
print("Max:", np.max(array))
print("Min:", np.min(array))

Max: 10
Min: 2


In [26]:
#Argmax/Argmin
#where it takes place,indices.
print("Argmax:", np.argmax(array))
print("Argmin:", np.argmin(array))

Argmax: 4
Argmin: 0


In [ ]:
#Aggregate Function make you code short and sweet. They're the best.